version: '3'

services:
  jupyter-notebooks:
    image: jupyter/all-spark-notebook:latest
    container_name: jupyter_notebook
    volumes: 
      - ./Notebooks:/home/jovyan
      - ./SetupScripts:/setupScripts
    command: /setupScripts/start.sh
    ports:
      - 1194:8888
